name: medical-cv-gpu
channels:
- pytorch
- conda-forge
- nvidia
- bioconda
- defaults
dependencies:
- python >= 3.6
- pip
- docopt
- joblib
- cython
#### standard data manipulation
- numpy
- pandas
#### working with standard images
- opencv # cv2 in Python
- pillow # PIL in Python
- imageio
- scikit-image # skimage in Python
#### working with medical images
- tifffile # to work with .tif and .tiff images
- pydicom # to load CT scans from DICOM format
- openslide # C library: to work with microscopy images (NDPI format)
- openslide-python # python library on top of openslide; openslide in Python
#### ml libraries
- scipy
- statsmodels
- scikit-learn # sklearn in Python
#### dl libraries
- tensorflow
- pytorch
- torchvision
#### cuda NOTE: 'nvidia' channel is required for cudatoolkit 11.1
- cudatoolkit=10.2
#### for replicating figures
- matplotlib
- seaborn
#### model interpretability
- captum # for interpreting pytorch models
#### for using this env as a kernel in jupyter notebooks
- jupyter
- nb_conda_kernels # to be able to choose a kernel
#### interactive time bars
- tqdm
