name: standard-ml
channels:
- conda-forge
dependencies:
- python >= 3.6
- pip
- docopt
- joblib
- cython
#### standard data manipulation
- numpy
- pandas
#### ml libraries
- scipy
- statsmodels
- scikit-learn
#### for replicating figures
- matplotlib
- seaborn
#### interactive progress bar
- tqdm
#### for using this env as a kernel in jupyter notebooks
- jupyter
- nb_conda_kernels
