name: standard-dl
channels:
- conda-forge
- pytorch
- bioconda
- defaults
dependencies:
- python >= 3.6
- pip
- docopt
- joblib
- cython
#### standard data manipulation
- numpy
- pandas
#### working with standard images
- opencv
- pillow
- imageio
- scikit-image
#### working with medical images
- tifffile # to work with .tif and .tiff images
- pydicom # to load CT scans from DICOM format
- openslide # C library: to work with microscopy images (NDPI format)
- openslide-python # python library on top of openslide
#### working with text
- spacy
- nltk
#### ml libraries
- scipy
- statsmodels
- scikit-learn
#### dl libraries
- tensorflow
- pytorch
- torchvision
#### for replicating figures
- matplotlib
- seaborn
#### model interpretability
- captum
#### for using this env as a kernel in jupyterlab
- jupyter
- nb_conda_kernels
